### ISSUE TITLE
renter contract error

### ISSUE THREAD

**Issue by ibralsmn** [onesolutionc/timeshare#2]
when open resservation i got error and hide fast and contenu open reservation 
and when select rent type i have error
```

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/ibralsmn/dev/workspace/odoo/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/ibralsmn/dev/workspace/odoo/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/ibralsmn/dev/workspace/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/home/ibralsmn/dev/workspace/odoo/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/home/ibralsmn/dev/workspace/odoo/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/ibralsmn/dev/workspace/odoo/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/ibralsmn/dev/workspace/odoo/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/ibralsmn/dev/workspace/odoo/odoo/http.py", line 910, in __call__
    return self.method(*args, **kw)
  File "/home/ibralsmn/dev/workspace/odoo/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/home/ibralsmn/dev/workspace/odoo/addons/web/controllers/main.py", line 1320, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/ibralsmn/dev/workspace/odoo/addons/web/controllers/main.py", line 1312, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/ibralsmn/dev/workspace/odoo/odoo/api.py", line 395, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/ibralsmn/dev/workspace/odoo/odoo/api.py", line 382, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/ibralsmn/dev/workspace/odoo/odoo/models.py", line 6055, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/home/ibralsmn/dev/workspace/odoo/odoo/models.py", line 5856, in _onchange_eval
    method_res = method(self)
  File "/home/ibralsmn/dev/workspace/odoo_addons/timeshare/models/timeshare_rent_contracts.py", line 67, in change_dates
    local_tz = pytz.timezone(self.env.user.tz)
  File "/home/ibralsmn/dev/workspace/odoo/venv/lib/python3.7/site-packages/pytz/__init__.py", line 163, in timezone
    if zone.upper() == 'UTC':
AttributeError: 'bool' object has no attribute 'upper'

```

**Comment by ibralsmn** [comment]
solved by set user time zone

**Comment by ibralsmn** [comment]
you must put validation when open this screen check if user timezone is set or not and not allow user to open form before set timezone

**Comment by one-msalah** [comment]
@ibralsmn test again now and give me feedback please
